# AUTOGENERATED FROM 'derp/queries/chat_settings.edgeql' WITH:
#     $ gel-py -I uburuntu/derp


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class ChatSettingsResult(NoPydanticValidation):
    id: uuid.UUID
    llm_memory: str | None


async def chat_settings(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: int,
) -> ChatSettingsResult | None:
    return await executor.query_single(
        """\
        select telegram::Chat {
            llm_memory,
        } filter .chat_id = <int64>$chat_id;\
        """,
        chat_id=chat_id,
    )
