# AUTOGENERATED FROM 'derp/queries/cleanup_expired_updates.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import gel


async def cleanup_expired_updates(
    executor: gel.AsyncIOExecutor,
) -> int:
    return await executor.query_single(
        """\
        # Cleanup expired updates (returns count of deleted updates)
        select count((delete telegram::ExpiredBotUpdates));\
        """,
    )
