# AUTOGENERATED FROM 'derp/queries/update_chat_settings.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema

        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateChatSettingsResult(NoPydanticValidation):
    id: uuid.UUID


async def update_chat_settings(
    executor: gel.AsyncIOExecutor,
    *,
    llm_memory: str | None = None,
    chat_id: int,
) -> UpdateChatSettingsResult | None:
    return await executor.query_single(
        """\
        update telegram::Chat
        filter .chat_id = <int64>$chat_id
        set {
            llm_memory := <optional str>$llm_memory
        };\
        """,
        llm_memory=llm_memory,
        chat_id=chat_id,
    )
