# AUTOGENERATED FROM 'derp/queries/upsert_chat.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpsertChatResult(NoPydanticValidation):
    id: uuid.UUID


async def upsert_chat(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: int,
    type: str,
    title: str | None = None,
    username: str | None = None,
    first_name: str | None = None,
    last_name: str | None = None,
    is_forum: bool | None = None,
) -> UpsertChatResult:
    return await executor.query_single(
        """\
        # Upsert Chat (insert or update based on chat_id)
        insert telegram::Chat {
            chat_id := <int64>$chat_id,
            type := <str>$type,
            title := <optional str>$title,
            username := <optional str>$username,
            first_name := <optional str>$first_name,
            last_name := <optional str>$last_name,
            is_forum := <optional bool>$is_forum ?? false,
        }
        unless conflict on .chat_id
        else (
            update telegram::Chat
            set {
                type := <str>$type,
                title := <optional str>$title,
                username := <optional str>$username,
                first_name := <optional str>$first_name,
                last_name := <optional str>$last_name,
                is_forum := <optional bool>$is_forum ?? false,
            }
        );\
        """,
        chat_id=chat_id,
        type=type,
        title=title,
        username=username,
        first_name=first_name,
        last_name=last_name,
        is_forum=is_forum,
    )
