"""Provider-neutral values returned by feature executors."""

from __future__ import annotations

from dataclasses import dataclass

from derp.media.types import MediaFamily, normalize_mime_type


@dataclass(frozen=True, slots=True)
class MediaContent:
    """Immutable generated bytes with a validated media identity."""

    family: MediaFamily
    mime_type: str
    data: bytes

    def __post_init__(self) -> None:
        if not isinstance(self.family, MediaFamily):
            raise TypeError("media family must be a MediaFamily")
        if not isinstance(self.data, bytes):
            raise TypeError("media data must be immutable bytes")
        if not self.data:
            raise ValueError("media data must not be empty")
        mime_type = normalize_mime_type(self.mime_type)
        if not mime_type.startswith(f"{self.family.value}/"):
            raise ValueError("media MIME type must match its family")
        object.__setattr__(self, "mime_type", mime_type)

    @property
    def size_bytes(self) -> int:
        """Return the exact in-memory payload size."""
        return len(self.data)


@dataclass(frozen=True, slots=True)
class TextOutput:
    """Normalized text produced by a provider-backed feature."""

    text: str

    def __post_init__(self) -> None:
        normalized = self.text.strip()
        if not normalized:
            raise ValueError("text output must not be blank")
        object.__setattr__(self, "text", normalized)


__all__ = ["MediaContent", "TextOutput"]
