"""initial schema

Revision ID: 623cb476f96d
Revises:
Create Date: 2025-12-18 21:10:33.967723+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "623cb476f96d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("is_forum", sa.Boolean(), nullable=False),
        sa.Column("llm_memory", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(llm_memory) <= 1024", name="llm_memory_max_length"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_telegram_id"), "chats", ["telegram_id"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("language_code", sa.String(length=10), nullable=True),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("direction", sa.String(length=3), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("media_group_id", sa.String(length=255), nullable=True),
        sa.Column("attachment_type", sa.String(length=50), nullable=True),
        sa.Column("attachment_file_id", sa.String(length=255), nullable=True),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chat_id", "telegram_message_id", name="uq_messages_chat_message"
        ),
    )
    op.create_index(
        "idx_messages_chat_recent",
        "messages",
        ["chat_id", "created_at", "telegram_message_id"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_index(
        "idx_messages_telegram_date",
        "messages",
        ["chat_id", "telegram_date"],
        unique=False,
    )
    op.create_index(
        "idx_messages_user",
        "messages",
        ["user_id"],
        unique=False,
        postgresql_where="user_id IS NOT NULL",
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_index(
        "idx_messages_user",
        table_name="messages",
        postgresql_where="user_id IS NOT NULL",
    )
    op.drop_index("idx_messages_telegram_date", table_name="messages")
    op.drop_index(
        "idx_messages_chat_recent",
        table_name="messages",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_table("messages")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_chats_telegram_id"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
