"""add credit system tables

Revision ID: cb4a8332d64d
Revises: 623cb476f96d
Create Date: 2025-12-19 15:33:03.869595+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb4a8332d64d"
down_revision: str | None = "623cb476f96d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=50), nullable=True),
        sa.Column("model_id", sa.String(length=100), nullable=True),
        sa.Column("telegram_charge_id", sa.String(length=100), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_transactions_chat_id"),
        "credit_transactions",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_transactions_idempotency_key"),
        "credit_transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_credit_transactions_type"),
        "credit_transactions",
        ["type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_credit_transactions_user_id"),
        "credit_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "daily_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "chat_id", "usage_date", name="uq_daily_usage"),
    )
    op.create_index(
        op.f("ix_daily_usage_chat_id"), "daily_usage", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_usage_usage_date"), "daily_usage", ["usage_date"], unique=False
    )
    op.create_index(
        op.f("ix_daily_usage_user_id"), "daily_usage", ["user_id"], unique=False
    )
    # Backfill-safe: default to 0 so existing rows migrate cleanly
    op.add_column(
        "chats",
        sa.Column("credits", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "users",
        sa.Column("credits", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "credits")
    op.drop_column("chats", "credits")
    op.drop_index(op.f("ix_daily_usage_user_id"), table_name="daily_usage")
    op.drop_index(op.f("ix_daily_usage_usage_date"), table_name="daily_usage")
    op.drop_index(op.f("ix_daily_usage_chat_id"), table_name="daily_usage")
    op.drop_table("daily_usage")
    op.drop_index(
        op.f("ix_credit_transactions_user_id"), table_name="credit_transactions"
    )
    op.drop_index(op.f("ix_credit_transactions_type"), table_name="credit_transactions")
    op.drop_index(
        op.f("ix_credit_transactions_idempotency_key"), table_name="credit_transactions"
    )
    op.drop_index(
        op.f("ix_credit_transactions_chat_id"), table_name="credit_transactions"
    )
    op.drop_table("credit_transactions")
    # ### end Alembic commands ###
