"""add durable wallet and operation ledger

Revision ID: bf4d56d8cdc9
Revises: 9f463771532f
Create Date: 2026-07-20 21:21:41.157823+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf4d56d8cdc9"
down_revision: str | None = "9f463771532f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_quotes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.String(length=255), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("feature", sa.String(length=32), nullable=False),
        sa.Column("model_key", sa.String(length=32), nullable=False),
        sa.Column("provider_model_id", sa.String(length=100), nullable=False),
        sa.Column("context_band", sa.String(length=16), nullable=False),
        sa.Column("variant", sa.String(length=64), nullable=False),
        sa.Column("amount_credits", sa.Integer(), nullable=False),
        sa.Column(
            "estimated_provider_cost_usd",
            sa.Numeric(precision=18, scale=8),
            nullable=False,
        ),
        sa.Column("pricing_version", sa.String(length=32), nullable=False),
        sa.Column("catalog_verified_on", sa.Date(), nullable=False),
        sa.Column(
            "pricing_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "context_band = ANY (ARRAY['small', 'medium', 'large', 'maximum'])",
            name="operation_quote_context_band_allowed",
        ),
        sa.CheckConstraint(
            "amount_credits >= 0", name="operation_quote_amount_non_negative"
        ),
        sa.CheckConstraint(
            "estimated_provider_cost_usd >= 0",
            name="operation_quote_provider_cost_non_negative",
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name="operation_quote_expiry_after_creation"
        ),
        sa.CheckConstraint(
            "thread_id IS NULL OR thread_id > 0", name="operation_quote_thread_positive"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "operation_id", name="uq_operation_quote_operation"),
        sa.UniqueConstraint("operation_id"),
        sa.UniqueConstraint("request_key"),
    )
    op.create_index(
        "idx_operation_quote_scope",
        "operation_quotes",
        ["chat_id", "thread_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_quotes_chat_id"),
        "operation_quotes",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operation_quotes_requester_id"),
        "operation_quotes",
        ["requester_id"],
        unique=False,
    )
    op.create_table(
        "personal_spend_consents",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(enabled AND revoked_at IS NULL) OR (NOT enabled AND revoked_at IS NOT NULL)",
            name="personal_spend_consent_state_complete",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "chat_id"),
    )
    op.create_table(
        "purchase_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("payer_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column("target_chat_id", sa.Uuid(), nullable=True),
        sa.Column("product_kind", sa.String(length=16), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("product_version", sa.String(length=32), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subscription_period_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(product_kind = 'subscription' AND subscription_period_seconds = 2592000) OR (product_kind = 'top_up' AND subscription_period_seconds IS NULL)",
            name="purchase_intent_subscription_period_matches",
        ),
        sa.CheckConstraint("currency = 'XTR'", name="purchase_intent_currency_xtr"),
        sa.CheckConstraint(
            "product_kind = ANY (ARRAY['top_up', 'subscription'])",
            name="purchase_intent_product_kind_allowed",
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['pending', 'prechecked', 'fulfilled', 'expired', 'canceled', 'needs_review'])",
            name="purchase_intent_status_allowed",
        ),
        sa.CheckConstraint(
            "credits > 0 AND stars > 0", name="purchase_intent_amounts_positive"
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name="purchase_intent_expiry_after_creation"
        ),
        sa.CheckConstraint(
            "num_nonnulls(target_user_id, target_chat_id) = 1",
            name="purchase_intent_exactly_one_target",
        ),
        sa.ForeignKeyConstraint(["payer_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_chat_id"], ["chats.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_purchase_intents_payer_user_id"),
        "purchase_intents",
        ["payer_user_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.String(length=64), nullable=False),
        sa.Column("plan_version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "renewal_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['active', 'canceled', 'expired'])",
            name="subscription_status_allowed",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("chat_id", sa.Uuid(), nullable=True),
        sa.Column(
            "debt_credits", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("debt_credits >= 0", name="wallet_debt_non_negative"),
        sa.CheckConstraint(
            "num_nonnulls(user_id, chat_id) = 1", name="wallet_exactly_one_owner"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_wallet_chat",
        "wallets",
        ["chat_id"],
        unique=True,
        postgresql_where=sa.text("chat_id IS NOT NULL"),
    )
    op.create_index(
        "uq_wallet_user",
        "wallets",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.create_table(
        "paid_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=True),
        sa.Column("funding_authorization", sa.String(length=16), nullable=True),
        sa.Column(
            "state",
            sa.String(length=16),
            server_default=sa.text("'quoted'"),
            nullable=False,
        ),
        sa.Column(
            "delivery_state",
            sa.String(length=16),
            server_default=sa.text("'not_ready'"),
            nullable=False,
        ),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column(
            "result_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_state = ANY (ARRAY['not_ready', 'pending', 'delivering', 'delivered', 'uncertain', 'failed', 'expired'])",
            name="paid_operation_delivery_state_allowed",
        ),
        sa.CheckConstraint(
            "funding_authorization IS NULL OR funding_authorization = ANY (ARRAY['chat', 'private', 'once', 'always'])",
            name="paid_operation_funding_authorization_allowed",
        ),
        sa.CheckConstraint(
            "state = ANY (ARRAY['quoted', 'reserved', 'executing', 'captured', 'released', 'reversed', 'canceled', 'failed'])",
            name="paid_operation_state_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id", "id"],
            ["operation_quotes.id", "operation_quotes.operation_id"],
            name="fk_paid_operation_matching_quote",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "wallet_id", name="uq_paid_operation_wallet"),
        sa.UniqueConstraint("quote_id"),
    )
    op.create_index(
        "idx_paid_operation_delivery_reconciliation",
        "paid_operations",
        ["delivery_state", "updated_at"],
        unique=False,
    )
    op.create_index(
        "idx_paid_operation_reconciliation",
        "paid_operations",
        ["state", "updated_at"],
        unique=False,
    )
    op.create_table(
        "payment_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_intent_id", sa.Uuid(), nullable=True),
        sa.Column("telegram_charge_id", sa.String(length=255), nullable=False),
        sa.Column("provider_charge_id", sa.String(length=255), nullable=False),
        sa.Column("payer_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("payload_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_first_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "subscription_expiration_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'received'"),
            nullable=False,
        ),
        sa.Column("clawed_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'XTR'", name="payment_receipt_currency_xtr"),
        sa.CheckConstraint(
            "status = ANY (ARRAY['received', 'fulfilled', 'clawed_back', 'needs_review'])",
            name="payment_receipt_status_allowed",
        ),
        sa.CheckConstraint(
            "NOT is_first_recurring OR is_recurring",
            name="payment_receipt_first_recurring_matches",
        ),
        sa.CheckConstraint(
            "subscription_expiration_at IS NULL OR is_recurring",
            name="payment_receipt_subscription_fields_match",
        ),
        sa.CheckConstraint("total_amount > 0", name="payment_receipt_amount_positive"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_charge_id"),
    )
    op.create_index(
        "idx_payment_receipt_intent_created",
        "payment_receipts",
        ["purchase_intent_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_receipts_payer_telegram_id"),
        "payment_receipts",
        ["payer_telegram_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_receipts_payload_token_hash"),
        "payment_receipts",
        ["payload_token_hash"],
        unique=False,
    )
    op.create_table(
        "deferred_tool_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("callback_token_hash", sa.String(length=64), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("tool_name", sa.String(length=64), nullable=False),
        sa.Column("tool_call_id", sa.String(length=255), nullable=False),
        sa.Column(
            "validated_arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "original_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("history_schema_version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['pending', 'approved', 'denied', 'expired', 'resumed'])",
            name="deferred_tool_status_allowed",
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name="deferred_tool_expiry_after_creation"
        ),
        sa.CheckConstraint("message_id > 0", name="deferred_tool_message_positive"),
        sa.CheckConstraint(
            "thread_id IS NULL OR thread_id > 0", name="deferred_tool_thread_positive"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["paid_operations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"], ["operation_quotes.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("callback_token_hash"),
        sa.UniqueConstraint("operation_id"),
        sa.UniqueConstraint("quote_id"),
    )
    op.create_index(
        "idx_deferred_tool_expiry",
        "deferred_tool_requests",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deferred_tool_requests_chat_id"),
        "deferred_tool_requests",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deferred_tool_requests_requester_id"),
        "deferred_tool_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_table(
        "subscription_cycles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("payment_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("allowance_credits", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['active', 'expired', 'clawed_back'])",
            name="subscription_cycle_status_allowed",
        ),
        sa.CheckConstraint(
            "allowance_credits > 0", name="subscription_cycle_allowance_positive"
        ),
        sa.CheckConstraint(
            "period_end > period_start", name="subscription_cycle_period_order"
        ),
        sa.ForeignKeyConstraint(
            ["payment_receipt_id"], ["payment_receipts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_receipt_id"),
        sa.UniqueConstraint(
            "subscription_id", "period_end", name="uq_subscription_cycle_period_end"
        ),
    )
    op.create_index(
        op.f("ix_subscription_cycles_subscription_id"),
        "subscription_cycles",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "wallet_lots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("payment_receipt_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_cycle_id", sa.Uuid(), nullable=True),
        sa.Column("granted_credits", sa.Integer(), nullable=False),
        sa.Column("available_credits", sa.Integer(), nullable=False),
        sa.Column(
            "reserved_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "consumed_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "expired_credits", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "clawed_back_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "debt_offset_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'allowance' AND subscription_cycle_id IS NOT NULL AND expires_at IS NOT NULL) OR (kind = 'purchased' AND subscription_cycle_id IS NULL AND expires_at IS NULL)",
            name="wallet_lot_kind_source_matches",
        ),
        sa.CheckConstraint(
            "kind = ANY (ARRAY['allowance', 'purchased'])",
            name="wallet_lot_kind_allowed",
        ),
        sa.CheckConstraint(
            "available_credits + reserved_credits + consumed_credits + expired_credits + clawed_back_credits + debt_offset_credits = granted_credits",
            name="wallet_lot_accounting_balanced",
        ),
        sa.CheckConstraint(
            "granted_credits >= 0 AND available_credits >= 0 AND reserved_credits >= 0 AND consumed_credits >= 0 AND expired_credits >= 0 AND clawed_back_credits >= 0 AND debt_offset_credits >= 0",
            name="wallet_lot_counters_non_negative",
        ),
        sa.CheckConstraint(
            "num_nonnulls(payment_receipt_id, subscription_cycle_id) <= 1",
            name="wallet_lot_one_source",
        ),
        sa.ForeignKeyConstraint(
            ["payment_receipt_id"], ["payment_receipts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_cycle_id"], ["subscription_cycles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "wallet_id", name="uq_wallet_lot_wallet"),
    )
    op.create_index(
        "idx_wallet_lots_reservation_order",
        "wallet_lots",
        ["wallet_id", "kind", "expires_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("available_credits > 0"),
    )
    op.create_index(
        op.f("ix_wallet_lots_wallet_id"), "wallet_lots", ["wallet_id"], unique=False
    )
    op.create_index(
        "uq_wallet_lot_payment_receipt",
        "wallet_lots",
        ["payment_receipt_id"],
        unique=True,
        postgresql_where=sa.text("payment_receipt_id IS NOT NULL"),
    )
    op.create_index(
        "uq_wallet_lot_subscription_cycle",
        "wallet_lots",
        ["subscription_cycle_id"],
        unique=True,
        postgresql_where=sa.text("subscription_cycle_id IS NOT NULL"),
    )
    op.create_table(
        "operation_allocations",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_lot_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("amount_credits", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_credits > 0", name="operation_allocation_amount_positive"
        ),
        sa.ForeignKeyConstraint(
            ["operation_id", "wallet_id"],
            ["paid_operations.id", "paid_operations.wallet_id"],
            name="fk_operation_allocation_operation_wallet",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["wallet_lot_id", "wallet_id"],
            ["wallet_lots.id", "wallet_lots.wallet_id"],
            name="fk_operation_allocation_lot_wallet",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("operation_id", "wallet_lot_id"),
    )
    op.create_table(
        "wallet_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_lot_id", sa.Uuid(), nullable=True),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("payment_receipt_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=24), nullable=False),
        sa.Column("amount_credits", sa.Integer(), nullable=False),
        sa.Column("available_after", sa.Integer(), nullable=False),
        sa.Column("reserved_after", sa.Integer(), nullable=False),
        sa.Column("consumed_after", sa.Integer(), nullable=False),
        sa.Column("wallet_debt_after", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type = ANY (ARRAY['grant', 'reserve', 'capture', 'release', 'reversal', 'expire', 'clawback', 'debt_incurred', 'debt_offset'])",
            name="wallet_ledger_event_allowed",
        ),
        sa.CheckConstraint("amount_credits > 0", name="wallet_ledger_amount_positive"),
        sa.CheckConstraint(
            "available_after >= 0 AND reserved_after >= 0 AND consumed_after >= 0 AND wallet_debt_after >= 0",
            name="wallet_ledger_snapshots_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id", "wallet_id"],
            ["paid_operations.id", "paid_operations.wallet_id"],
            name="fk_wallet_ledger_operation_wallet",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_receipt_id"], ["payment_receipts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["wallet_lot_id", "wallet_id"],
            ["wallet_lots.id", "wallet_lots.wallet_id"],
            name="fk_wallet_ledger_lot_wallet",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "idx_wallet_ledger_created",
        "wallet_ledger_entries",
        ["wallet_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_ledger_entries_event_type"),
        "wallet_ledger_entries",
        ["event_type"],
        unique=False,
    )
    op.execute(
        """
        INSERT INTO wallets (id, user_id, debt_credits)
        SELECT gen_random_uuid(), users.id, 0
        FROM users
        ON CONFLICT (user_id) WHERE user_id IS NOT NULL DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO wallets (id, chat_id, debt_credits)
        SELECT gen_random_uuid(), chats.id, 0
        FROM chats
        ON CONFLICT (chat_id) WHERE chat_id IS NOT NULL DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO wallet_lots (
            id, wallet_id, kind, granted_credits, available_credits
        )
        SELECT gen_random_uuid(), wallets.id, 'purchased', users.credits, users.credits
        FROM wallets
        JOIN users ON users.id = wallets.user_id
        WHERE users.credits > 0
        """
    )
    op.execute(
        """
        INSERT INTO wallet_lots (
            id, wallet_id, kind, granted_credits, available_credits
        )
        SELECT gen_random_uuid(), wallets.id, 'purchased', chats.credits, chats.credits
        FROM wallets
        JOIN chats ON chats.id = wallets.chat_id
        WHERE chats.credits > 0
        """
    )
    op.execute(
        """
        CREATE FUNCTION derp_reject_immutable_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'immutable billing record cannot be changed'
                USING ERRCODE = '55000';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER operation_quotes_immutable
        BEFORE UPDATE OR DELETE ON operation_quotes
        FOR EACH ROW EXECUTE FUNCTION derp_reject_immutable_mutation()
        """
    )
    op.execute(
        """
        CREATE TRIGGER wallet_ledger_entries_append_only
        BEFORE UPDATE OR DELETE ON wallet_ledger_entries
        FOR EACH ROW EXECUTE FUNCTION derp_reject_immutable_mutation()
        """
    )
    op.execute(
        """
        CREATE FUNCTION derp_validate_allowance_lot()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            cycle_user_id uuid;
            cycle_period_end timestamptz;
            wallet_user_id uuid;
        BEGIN
            IF NEW.kind <> 'allowance' THEN
                RETURN NEW;
            END IF;

            SELECT subscriptions.user_id, subscription_cycles.period_end
            INTO cycle_user_id, cycle_period_end
            FROM subscription_cycles
            JOIN subscriptions
              ON subscriptions.id = subscription_cycles.subscription_id
            WHERE subscription_cycles.id = NEW.subscription_cycle_id;

            SELECT wallets.user_id
            INTO wallet_user_id
            FROM wallets
            WHERE wallets.id = NEW.wallet_id;

            IF wallet_user_id IS NULL OR wallet_user_id <> cycle_user_id THEN
                RAISE EXCEPTION 'allowance lot owner must match subscription owner'
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'wallet_lot_allowance_owner_matches';
            END IF;
            IF NEW.expires_at IS DISTINCT FROM cycle_period_end THEN
                RAISE EXCEPTION 'allowance expiry must match its cycle'
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'wallet_lot_allowance_expiry_matches';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER wallet_lot_allowance_source_valid
        BEFORE INSERT OR UPDATE OF wallet_id, kind, subscription_cycle_id, expires_at
        ON wallet_lots
        FOR EACH ROW EXECUTE FUNCTION derp_validate_allowance_lot()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER wallet_lot_allowance_source_valid ON wallet_lots")
    op.execute("DROP FUNCTION derp_validate_allowance_lot()")
    op.execute(
        "DROP TRIGGER wallet_ledger_entries_append_only ON wallet_ledger_entries"
    )
    op.execute("DROP TRIGGER operation_quotes_immutable ON operation_quotes")
    op.execute("DROP FUNCTION derp_reject_immutable_mutation()")
    op.drop_index(
        op.f("ix_wallet_ledger_entries_event_type"), table_name="wallet_ledger_entries"
    )
    op.drop_index("idx_wallet_ledger_created", table_name="wallet_ledger_entries")
    op.drop_table("wallet_ledger_entries")
    op.drop_table("operation_allocations")
    op.drop_index(
        "uq_wallet_lot_subscription_cycle",
        table_name="wallet_lots",
        postgresql_where=sa.text("subscription_cycle_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_wallet_lot_payment_receipt",
        table_name="wallet_lots",
        postgresql_where=sa.text("payment_receipt_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_wallet_lots_wallet_id"), table_name="wallet_lots")
    op.drop_index(
        "idx_wallet_lots_reservation_order",
        table_name="wallet_lots",
        postgresql_where=sa.text("available_credits > 0"),
    )
    op.drop_table("wallet_lots")
    op.drop_index(
        op.f("ix_subscription_cycles_subscription_id"), table_name="subscription_cycles"
    )
    op.drop_table("subscription_cycles")
    op.drop_index(
        op.f("ix_deferred_tool_requests_requester_id"),
        table_name="deferred_tool_requests",
    )
    op.drop_index(
        op.f("ix_deferred_tool_requests_chat_id"), table_name="deferred_tool_requests"
    )
    op.drop_index("idx_deferred_tool_expiry", table_name="deferred_tool_requests")
    op.drop_table("deferred_tool_requests")
    op.drop_index(
        op.f("ix_payment_receipts_payload_token_hash"), table_name="payment_receipts"
    )
    op.drop_index(
        op.f("ix_payment_receipts_payer_telegram_id"), table_name="payment_receipts"
    )
    op.drop_index("idx_payment_receipt_intent_created", table_name="payment_receipts")
    op.drop_table("payment_receipts")
    op.drop_index("idx_paid_operation_reconciliation", table_name="paid_operations")
    op.drop_index(
        "idx_paid_operation_delivery_reconciliation", table_name="paid_operations"
    )
    op.drop_table("paid_operations")
    op.drop_index(
        "uq_wallet_user",
        table_name="wallets",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_wallet_chat",
        table_name="wallets",
        postgresql_where=sa.text("chat_id IS NOT NULL"),
    )
    op.drop_table("wallets")
    op.drop_table("subscriptions")
    op.drop_index(
        op.f("ix_purchase_intents_payer_user_id"), table_name="purchase_intents"
    )
    op.drop_table("purchase_intents")
    op.drop_table("personal_spend_consents")
    op.drop_index(
        op.f("ix_operation_quotes_requester_id"), table_name="operation_quotes"
    )
    op.drop_index(op.f("ix_operation_quotes_chat_id"), table_name="operation_quotes")
    op.drop_index("idx_operation_quote_scope", table_name="operation_quotes")
    op.drop_table("operation_quotes")
    # ### end Alembic commands ###
