"""add release safety subsystems

Revision ID: 89f60115a175
Revises: dcca6f548b5b
Create Date: 2026-07-28 13:31:37.309745+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89f60115a175"
down_revision: str | None = "dcca6f548b5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_LEDGER_EVENTS = (
    "grant",
    "reserve",
    "capture",
    "release",
    "reversal",
    "expire",
    "clawback",
    "debt_incurred",
    "debt_offset",
)
_NEW_LEDGER_EVENTS = (*_OLD_LEDGER_EVENTS, "debt_restored", "debt_reopened")


def _ledger_event_check(events: tuple[str, ...]) -> str:
    values = ", ".join(f"'{event}'" for event in events)
    return f"event_type = ANY (ARRAY[{values}])"


def _require_empty_legacy_debt() -> None:
    connection = op.get_bind()
    unsafe = int(
        connection.scalar(
            sa.text(
                """
                SELECT
                    (SELECT count(*) FROM wallets WHERE debt_credits <> 0)
                    + (SELECT count(*) FROM wallet_lots WHERE debt_offset_credits <> 0)
                    + (
                        SELECT count(*)
                        FROM wallet_lots AS lots
                        JOIN wallets ON wallets.id = lots.wallet_id
                        LEFT JOIN payment_receipts AS receipts
                          ON receipts.id = lots.payment_receipt_id
                        LEFT JOIN subscription_cycles AS cycles
                          ON cycles.id = lots.subscription_cycle_id
                        WHERE (
                              receipts.status = 'clawed_back'
                              OR cycles.status = 'clawed_back'
                          )
                          AND lots.reserved_credits + lots.consumed_credits > 0
                          AND wallets.debt_credits = 0
                    )
                """
            )
        )
        or 0
    )
    if unsafe:
        raise RuntimeError("legacy wallet debt requires reviewed provenance backfill")


def _require_empty_new_subsystems() -> None:
    connection = op.get_bind()
    durable_rows = int(
        connection.scalar(
            sa.text(
                """
                SELECT
                    (SELECT count(*) FROM payment_update_inbox)
                    + (SELECT count(*) FROM legal_acceptances)
                    + (SELECT count(*) FROM support_requests)
                    + (SELECT count(*) FROM payment_refund_requests)
                    + (SELECT count(*) FROM subscription_renewal_commands)
                    + (SELECT count(*) FROM wallet_debt_sources)
                    + (SELECT count(*) FROM wallet_debt_repayment_allocations)
                    + (
                        SELECT count(*)
                        FROM inference_usage_records
                        WHERE actual_model_id IS NOT NULL
                           OR downstream_provider IS NOT NULL
                           OR NOT route_policy_matched
                    )
                """
            )
        )
        or 0
    )
    if durable_rows:
        raise RuntimeError("release safety downgrade would discard durable state")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _require_empty_legacy_debt()
    op.create_table(
        "payment_update_inbox",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_update_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload_token_hash", sa.String(length=64), nullable=False),
        sa.Column("telegram_charge_id", sa.String(length=255), nullable=False),
        sa.Column("provider_charge_id", sa.String(length=255), nullable=True),
        sa.Column("payer_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("reply_chat_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "reply_language",
            sa.String(length=8),
            server_default=sa.text("'en'"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_first_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "subscription_expiration_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "reply_attempt_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settlement_state", sa.String(length=16), nullable=True),
        sa.Column("attention_reason", sa.String(length=64), nullable=True),
        sa.Column("last_failure_code", sa.String(length=64), nullable=True),
        sa.Column(
            "reply_status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status::text = 'processing'::text AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL OR status::text <> 'processing'::text AND lease_token IS NULL AND lease_expires_at IS NULL",
            name="payment_update_inbox_lease_matches_status",
        ),
        sa.CheckConstraint(
            "currency::text = 'XTR'::text", name="payment_update_inbox_currency_xtr"
        ),
        sa.CheckConstraint(
            "kind::text = 'successful_payment'::text OR NOT is_recurring AND NOT is_first_recurring AND subscription_expiration_at IS NULL",
            name="payment_update_inbox_recurring_fields_match_kind",
        ),
        sa.CheckConstraint(
            "kind::text = ANY (ARRAY['successful_payment'::text, 'refunded_payment'::text])",
            name="payment_update_inbox_kind_allowed",
        ),
        sa.CheckConstraint(
            "reply_status::text = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'skipped'::text])",
            name="payment_update_inbox_reply_status_allowed",
        ),
        sa.CheckConstraint(
            "settlement_state IS NULL OR (settlement_state::text = ANY (ARRAY['fulfilled'::text, 'clawed_back'::text, 'refunded'::text]))",
            name="payment_update_inbox_settlement_state_allowed",
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'attention'::text])",
            name="payment_update_inbox_status_allowed",
        ),
        sa.CheckConstraint(
            "NOT is_first_recurring OR is_recurring",
            name="payment_update_inbox_first_recurring_matches",
        ),
        sa.CheckConstraint(
            "telegram_update_id >= 0 AND total_amount > 0 "
            "AND attempt_count >= 0 AND reply_attempt_count >= 0",
            name="payment_update_inbox_values_valid",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_update_id"),
    )
    op.create_index(
        "idx_payment_update_inbox_due",
        "payment_update_inbox",
        ["status", "next_attempt_at", "telegram_update_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_update_inbox_telegram_charge_id"),
        "payment_update_inbox",
        ["telegram_charge_id"],
        unique=False,
    )
    op.create_table(
        "legal_acceptances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "document::text = 'terms'::text", name="legal_acceptance_document_allowed"
        ),
        sa.CheckConstraint(
            "source::text = ANY (ARRAY['terms_command'::text, 'purchase_gate'::text])",
            name="legal_acceptance_source_allowed",
        ),
        sa.CheckConstraint(
            "length(btrim(version::text)) > 0", name="legal_acceptance_version_nonblank"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "document",
            "version",
            name="legal_acceptance_user_document_version_unique",
        ),
    )
    op.create_index(
        op.f("ix_legal_acceptances_user_id"),
        "legal_acceptances",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "support_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference", sa.String(length=16), nullable=False),
        sa.Column("requester_user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'open'"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status::text = 'open'::text AND resolved_at IS NULL OR status::text = 'resolved'::text AND resolved_at IS NOT NULL",
            name="support_request_resolution_complete",
        ),
        sa.CheckConstraint(
            "kind::text = ANY (ARRAY['payment'::text, 'refund'::text, 'privacy'::text, 'access'::text])",
            name="support_request_kind_allowed",
        ),
        sa.CheckConstraint(
            "source::text = ANY (ARRAY['support'::text, 'paysupport'::text, 'privacy'::text])",
            name="support_request_source_allowed",
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['open'::text, 'resolved'::text])",
            name="support_request_status_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference", name="support_request_reference_unique"),
    )
    op.create_index(
        op.f("ix_support_requests_requester_user_id"),
        "support_requests",
        ["requester_user_id"],
        unique=False,
    )
    op.create_index(
        "support_request_one_open_kind_per_user",
        "support_requests",
        ["requester_user_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "payment_refund_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("requester_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status::text = 'pending'::text AND submitted_at IS NULL OR status::text <> 'pending'::text AND submitted_at IS NOT NULL AND attempt_count > 0",
            name="payment_refund_request_submission_matches_status",
        ),
        sa.CheckConstraint(
            "status::text = 'reconciled'::text AND reconciled_at IS NOT NULL OR status::text <> 'reconciled'::text AND reconciled_at IS NULL",
            name="payment_refund_request_reconciliation_matches_status",
        ),
        sa.CheckConstraint(
            "(status::text = ANY (ARRAY['accepted'::text, 'reconciled'::text])) AND accepted_at IS NOT NULL OR (status::text <> ALL (ARRAY['accepted'::text, 'reconciled'::text])) AND accepted_at IS NULL",
            name="payment_refund_request_acceptance_matches_status",
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['pending'::text, 'submitting'::text, 'accepted'::text, 'rejected'::text, 'needs_review'::text, 'reconciled'::text])",
            name="payment_refund_request_status_allowed",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="payment_refund_request_attempt_count_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["payment_receipt_id"], ["payment_receipts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_refund_requests_payment_receipt_id"),
        "payment_refund_requests",
        ["payment_receipt_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payment_refund_requests_requester_telegram_id"),
        "payment_refund_requests",
        ["requester_telegram_id"],
        unique=False,
    )
    op.create_table(
        "subscription_renewal_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("payer_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_charge_id", sa.String(length=255), nullable=False),
        sa.Column("desired_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="subscription_renewal_command_attempt_count_nonnegative",
        ),
        sa.CheckConstraint(
            "(status::text = ANY (ARRAY['applied'::text, 'superseded'::text]) AND completed_at IS NOT NULL) OR (status::text <> ALL (ARRAY['applied'::text, 'superseded'::text]) AND completed_at IS NULL)",
            name="subscription_renewal_command_completion_matches_status",
        ),
        sa.CheckConstraint(
            "(status::text = 'processing'::text AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status::text <> 'processing'::text AND lease_token IS NULL AND lease_expires_at IS NULL)",
            name="subscription_renewal_command_lease_matches_status",
        ),
        sa.CheckConstraint(
            "payer_telegram_id > 0 AND length(btrim(telegram_charge_id)) > 0",
            name="subscription_renewal_command_provider_identity_valid",
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['pending'::text, 'processing'::text, 'applied'::text, 'superseded'::text, 'attention'::text])",
            name="subscription_renewal_command_status_allowed",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_subscription_renewal_command_due",
        "subscription_renewal_commands",
        ["status", "next_attempt_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_renewal_commands_subscription_id"),
        "subscription_renewal_commands",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "uq_subscription_renewal_command_active",
        "subscription_renewal_commands",
        ["subscription_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'processing', 'attention')"),
    )
    op.create_table(
        "wallet_debt_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("source_wallet_lot_id", sa.Uuid(), nullable=False),
        sa.Column("incurred_credits", sa.Integer(), nullable=False),
        sa.Column("outstanding_credits", sa.Integer(), nullable=False),
        sa.Column(
            "recovered_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "incurred_credits > 0", name="wallet_debt_source_incurred_positive"
        ),
        sa.CheckConstraint(
            "outstanding_credits >= 0 AND recovered_credits >= 0 AND (outstanding_credits + recovered_credits) <= incurred_credits",
            name="wallet_debt_source_counters_valid",
        ),
        sa.ForeignKeyConstraint(
            ["source_wallet_lot_id", "wallet_id"],
            ["wallet_lots.id", "wallet_lots.wallet_id"],
            name="fk_wallet_debt_source_lot_wallet",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "wallet_id", name="uq_wallet_debt_source_wallet"),
        sa.UniqueConstraint("source_wallet_lot_id", name="uq_wallet_debt_source_lot"),
    )
    op.create_index(
        "idx_wallet_debt_sources_open",
        "wallet_debt_sources",
        ["wallet_id", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("outstanding_credits > 0"),
    )
    op.create_table(
        "wallet_debt_repayment_allocations",
        sa.Column("debt_source_id", sa.Uuid(), nullable=False),
        sa.Column("repayment_wallet_lot_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("allocated_credits", sa.Integer(), nullable=False),
        sa.Column(
            "restored_credits",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "revoked_credits", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allocated_credits > 0", name="wallet_debt_repayment_allocated_positive"
        ),
        sa.CheckConstraint(
            "restored_credits >= 0 AND revoked_credits >= 0 AND (restored_credits + revoked_credits) <= allocated_credits",
            name="wallet_debt_repayment_counters_valid",
        ),
        sa.ForeignKeyConstraint(
            ["debt_source_id", "wallet_id"],
            ["wallet_debt_sources.id", "wallet_debt_sources.wallet_id"],
            name="fk_wallet_debt_repayment_source_wallet",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["repayment_wallet_lot_id", "wallet_id"],
            ["wallet_lots.id", "wallet_lots.wallet_id"],
            name="fk_wallet_debt_repayment_lot_wallet",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("debt_source_id", "repayment_wallet_lot_id"),
    )
    op.create_index(
        "idx_wallet_debt_repayments_active",
        "wallet_debt_repayment_allocations",
        ["debt_source_id", "created_at", "repayment_wallet_lot_id"],
        unique=False,
        postgresql_where=sa.text(
            "restored_credits + revoked_credits < allocated_credits"
        ),
    )
    op.add_column(
        "inference_usage_records",
        sa.Column("actual_model_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "inference_usage_records",
        sa.Column("downstream_provider", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "inference_usage_records",
        sa.Column(
            "route_policy_matched",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "inference_usage_actual_model_not_blank",
        "inference_usage_records",
        "actual_model_id IS NULL OR length(btrim(actual_model_id)) > 0",
    )
    op.create_check_constraint(
        "inference_usage_downstream_provider_not_blank",
        "inference_usage_records",
        "downstream_provider IS NULL OR length(btrim(downstream_provider)) > 0",
    )
    op.drop_constraint(
        "wallet_ledger_event_allowed",
        "wallet_ledger_entries",
        type_="check",
    )
    op.create_check_constraint(
        "wallet_ledger_event_allowed",
        "wallet_ledger_entries",
        _ledger_event_check(_NEW_LEDGER_EVENTS),
    )
    op.add_column(
        "purchase_intents", sa.Column("terms_acceptance_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_purchase_intents_terms_acceptance_id"),
        "purchase_intents",
        ["terms_acceptance_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_purchase_intent_terms_acceptance",
        "purchase_intents",
        "legal_acceptances",
        ["terms_acceptance_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _require_empty_new_subsystems()
    op.drop_constraint(
        "fk_purchase_intent_terms_acceptance",
        "purchase_intents",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_purchase_intents_terms_acceptance_id"), table_name="purchase_intents"
    )
    op.drop_column("purchase_intents", "terms_acceptance_id")
    op.drop_constraint(
        "wallet_ledger_event_allowed",
        "wallet_ledger_entries",
        type_="check",
    )
    op.create_check_constraint(
        "wallet_ledger_event_allowed",
        "wallet_ledger_entries",
        _ledger_event_check(_OLD_LEDGER_EVENTS),
    )
    op.drop_constraint(
        "inference_usage_downstream_provider_not_blank",
        "inference_usage_records",
        type_="check",
    )
    op.drop_constraint(
        "inference_usage_actual_model_not_blank",
        "inference_usage_records",
        type_="check",
    )
    op.drop_column("inference_usage_records", "route_policy_matched")
    op.drop_column("inference_usage_records", "downstream_provider")
    op.drop_column("inference_usage_records", "actual_model_id")
    op.drop_index(
        "uq_subscription_renewal_command_active",
        table_name="subscription_renewal_commands",
        postgresql_where=sa.text("status IN ('pending', 'processing', 'attention')"),
    )
    op.drop_index(
        op.f("ix_subscription_renewal_commands_subscription_id"),
        table_name="subscription_renewal_commands",
    )
    op.drop_index(
        "idx_subscription_renewal_command_due",
        table_name="subscription_renewal_commands",
    )
    op.drop_table("subscription_renewal_commands")
    op.drop_index(
        "idx_wallet_debt_repayments_active",
        table_name="wallet_debt_repayment_allocations",
        postgresql_where=sa.text(
            "restored_credits + revoked_credits < allocated_credits"
        ),
    )
    op.drop_table("wallet_debt_repayment_allocations")
    op.drop_index(
        "idx_wallet_debt_sources_open",
        table_name="wallet_debt_sources",
        postgresql_where=sa.text("outstanding_credits > 0"),
    )
    op.drop_table("wallet_debt_sources")
    op.drop_index(
        op.f("ix_payment_refund_requests_requester_telegram_id"),
        table_name="payment_refund_requests",
    )
    op.drop_index(
        op.f("ix_payment_refund_requests_payment_receipt_id"),
        table_name="payment_refund_requests",
    )
    op.drop_table("payment_refund_requests")
    op.drop_index(
        "support_request_one_open_kind_per_user",
        table_name="support_requests",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(
        op.f("ix_support_requests_requester_user_id"), table_name="support_requests"
    )
    op.drop_table("support_requests")
    op.drop_index(op.f("ix_legal_acceptances_user_id"), table_name="legal_acceptances")
    op.drop_table("legal_acceptances")
    op.drop_index(
        op.f("ix_payment_update_inbox_telegram_charge_id"),
        table_name="payment_update_inbox",
    )
    op.drop_index("idx_payment_update_inbox_due", table_name="payment_update_inbox")
    op.drop_table("payment_update_inbox")
    # ### end Alembic commands ###
