"""add chat context policy

Revision ID: 6bce7ab76920
Revises: 83675a9a2ab5
Create Date: 2026-07-20 19:24:46.697864+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bce7ab76920"
down_revision: str | None = "83675a9a2ab5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("admin_policy", sa.Text(), nullable=True))
    op.add_column(
        "chats",
        sa.Column(
            "ambient_history_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "chats",
        sa.Column(
            "context_notice_version",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.add_column(
        "chats",
        sa.Column(
            "retention_days", sa.Integer(), server_default=sa.text("30"), nullable=False
        ),
    )
    op.add_column(
        "chats",
        sa.Column("member_notice_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "chats",
        sa.Column(
            "shared_facts_member_edit",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "chats",
        sa.Column(
            "shared_credit_spending_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "chats",
        sa.Column(
            "expensive_tools_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "admin_policy_max_length",
        "chats",
        "admin_policy IS NULL OR length(admin_policy) <= 2048",
    )
    op.create_check_constraint(
        "chat_retention_days_allowed",
        "chats",
        "retention_days = ANY (ARRAY[7, 30, 90])",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_retention_days_allowed", "chats", type_="check")
    op.drop_constraint("admin_policy_max_length", "chats", type_="check")
    op.drop_column("chats", "expensive_tools_enabled")
    op.drop_column("chats", "shared_credit_spending_enabled")
    op.drop_column("chats", "shared_facts_member_edit")
    op.drop_column("chats", "member_notice_sent_at")
    op.drop_column("chats", "retention_days")
    op.drop_column("chats", "context_notice_version")
    op.drop_column("chats", "ambient_history_enabled")
    op.drop_column("chats", "admin_policy")
    # ### end Alembic commands ###
