"""add durable artifacts and delivery intents

Revision ID: aaa08fcdc5b5
Revises: bf4d56d8cdc9
Create Date: 2026-07-20 21:42:11.205805+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aaa08fcdc5b5"
down_revision: str | None = "bf4d56d8cdc9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=32), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind::text = ANY (ARRAY['image'::text, 'video'::text, 'audio'::text, 'document'::text])",
            name="artifact_kind_allowed",
        ),
        sa.CheckConstraint(
            "sha256::text ~ '^[0-9a-f]{64}$'::text", name="artifact_sha256_valid"
        ),
        sa.CheckConstraint(
            "storage_key::text ~ '^[0-9a-f]{32}$'::text",
            name="artifact_storage_key_opaque",
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name="artifact_expiry_after_creation"
        ),
        sa.CheckConstraint(
            "length(btrim(mime_type::text)) > 0 AND length(btrim(filename::text)) > 0",
            name="artifact_names_not_blank",
        ),
        sa.CheckConstraint("ordinal >= 0", name="artifact_ordinal_non_negative"),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 67108864", name="artifact_size_bounded"
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["paid_operations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "operation_id", "ordinal", name="uq_artifact_operation_ordinal"
        ),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        "idx_artifact_expiry", "artifacts", ["expires_at", "id"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_operation_id"), "artifacts", ["operation_id"], unique=False
    )
    op.create_table(
        "delivery_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("business_connection_id", sa.String(length=255), nullable=True),
        sa.Column("progress_message_id", sa.BigInteger(), nullable=True),
        sa.Column("resend_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.String(length=16),
            server_default=sa.text("'not_ready'"),
            nullable=False,
        ),
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "telegram_message_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("uncertain_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state::text = 'delivered'::text AND delivered_at IS NOT NULL OR state::text <> 'delivered'::text AND delivered_at IS NULL",
            name="delivery_delivered_timestamp_matches",
        ),
        sa.CheckConstraint(
            "state::text = 'uncertain'::text AND uncertain_at IS NOT NULL OR state::text <> 'uncertain'::text AND uncertain_at IS NULL",
            name="delivery_uncertain_timestamp_matches",
        ),
        sa.CheckConstraint(
            "state::text = ANY (ARRAY['failed'::text, 'expired'::text]) AND failed_at IS NOT NULL OR NOT (state::text = ANY (ARRAY['failed'::text, 'expired'::text])) AND failed_at IS NULL",
            name="delivery_failed_timestamp_matches",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(telegram_message_ids) = 'array'::text",
            name="delivery_message_ids_array",
        ),
        sa.CheckConstraint(
            "resend_token_hash::text ~ '^[0-9a-f]{64}$'::text",
            name="delivery_resend_token_hash_valid",
        ),
        sa.CheckConstraint(
            "state::text = ANY (ARRAY['not_ready'::text, 'pending'::text, 'delivering'::text, 'delivered'::text, 'uncertain'::text, 'failed'::text, 'expired'::text])",
            name="delivery_state_allowed",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name="delivery_attempt_count_non_negative"
        ),
        sa.CheckConstraint("chat_id <> 0", name="delivery_chat_nonzero"),
        sa.CheckConstraint(
            "expires_at > created_at", name="delivery_expiry_after_creation"
        ),
        sa.CheckConstraint(
            "progress_message_id IS NULL OR progress_message_id > 0",
            name="delivery_progress_positive",
        ),
        sa.CheckConstraint(
            "reply_to_message_id IS NULL OR reply_to_message_id > 0",
            name="delivery_reply_positive",
        ),
        sa.CheckConstraint(
            "thread_id IS NULL OR thread_id > 0", name="delivery_thread_positive"
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["paid_operations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id"),
        sa.UniqueConstraint("resend_token_hash"),
    )
    op.create_index(
        "idx_delivery_expiry", "delivery_intents", ["expires_at", "id"], unique=False
    )
    op.create_index(
        "idx_delivery_reconciliation",
        "delivery_intents",
        ["state", "updated_at"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION derp_reject_artifact_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'artifact metadata is immutable'
                USING ERRCODE = '55000';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER artifact_metadata_immutable
        BEFORE UPDATE ON artifacts
        FOR EACH ROW EXECUTE FUNCTION derp_reject_artifact_update()
        """
    )
    op.execute(
        """
        CREATE FUNCTION derp_validate_delivery_target_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF ROW(
                OLD.operation_id,
                OLD.chat_id,
                OLD.thread_id,
                OLD.reply_to_message_id,
                OLD.business_connection_id,
                OLD.resend_token_hash,
                OLD.expires_at,
                OLD.caption
            ) IS DISTINCT FROM ROW(
                NEW.operation_id,
                NEW.chat_id,
                NEW.thread_id,
                NEW.reply_to_message_id,
                NEW.business_connection_id,
                NEW.resend_token_hash,
                NEW.expires_at,
                NEW.caption
            ) THEN
                RAISE EXCEPTION 'delivery target is immutable'
                    USING ERRCODE = '55000';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER delivery_target_immutable
        BEFORE UPDATE ON delivery_intents
        FOR EACH ROW EXECUTE FUNCTION derp_validate_delivery_target_update()
        """
    )
    op.execute(
        """
        CREATE FUNCTION derp_sync_operation_delivery_state()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            UPDATE paid_operations
            SET delivery_state = NEW.state, updated_at = now()
            WHERE id = NEW.operation_id;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER delivery_state_sync
        AFTER INSERT OR UPDATE OF state ON delivery_intents
        FOR EACH ROW EXECUTE FUNCTION derp_sync_operation_delivery_state()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER delivery_state_sync ON delivery_intents")
    op.execute("DROP FUNCTION derp_sync_operation_delivery_state()")
    op.execute("DROP TRIGGER delivery_target_immutable ON delivery_intents")
    op.execute("DROP FUNCTION derp_validate_delivery_target_update()")
    op.execute("DROP TRIGGER artifact_metadata_immutable ON artifacts")
    op.execute("DROP FUNCTION derp_reject_artifact_update()")
    op.drop_index("idx_delivery_reconciliation", table_name="delivery_intents")
    op.drop_index("idx_delivery_expiry", table_name="delivery_intents")
    op.drop_table("delivery_intents")
    op.drop_index(op.f("ix_artifacts_operation_id"), table_name="artifacts")
    op.drop_index("idx_artifact_expiry", table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
