"""add versioned conversation projections

Revision ID: 48e3e16a99be
Revises: 6bce7ab76920
Create Date: 2026-07-20 19:37:10.256898+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48e3e16a99be"
down_revision: str | None = "6bce7ab76920"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "role",
            sa.String(length=16),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "capture_kind",
            sa.String(length=16),
            server_default=sa.text("'explicit'"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "source_schema_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "source_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "history_schema_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "history_dto",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "canonical_schema_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column(
            "canonical_projection",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.execute("UPDATE messages SET role = 'assistant' WHERE direction = 'out'")
    op.create_check_constraint(
        "message_role_allowed",
        "messages",
        "role::text = ANY (ARRAY['user'::text, 'assistant'::text])",
    )
    op.create_check_constraint(
        "message_capture_kind_allowed",
        "messages",
        "capture_kind::text = ANY (ARRAY['ambient'::text, 'explicit'::text])",
    )
    op.create_check_constraint(
        "message_projection_versions_positive",
        "messages",
        "source_schema_version >= 1 AND history_schema_version >= 1 "
        "AND canonical_schema_version >= 1",
    )
    op.create_index(
        "idx_messages_scope_history",
        "messages",
        ["chat_id", "thread_id", "telegram_date", "telegram_message_id"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_messages_scope_history",
        table_name="messages",
        postgresql_where="deleted_at IS NULL",
    )
    op.drop_constraint(
        "message_projection_versions_positive", "messages", type_="check"
    )
    op.drop_constraint("message_capture_kind_allowed", "messages", type_="check")
    op.drop_constraint("message_role_allowed", "messages", type_="check")
    op.drop_column("messages", "canonical_projection")
    op.drop_column("messages", "canonical_schema_version")
    op.drop_column("messages", "history_dto")
    op.drop_column("messages", "history_schema_version")
    op.drop_column("messages", "source_snapshot")
    op.drop_column("messages", "source_schema_version")
    op.drop_column("messages", "capture_kind")
    op.drop_column("messages", "role")
    # ### end Alembic commands ###
