"""add history retention and privacy tombstones

Revision ID: 02b5064d13e8
Revises: 48e3e16a99be
Create Date: 2026-07-20 20:11:16.852691+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02b5064d13e8"
down_revision: str | None = "48e3e16a99be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("privacy_deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "messages",
        sa.Column(
            "retention_expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() + '30 days'::interval)"),
            nullable=True,
        ),
    )
    # Legacy group history predates visible ambient-capture consent and cannot be
    # classified reliably. Conservatively remove it instead of relabeling it.
    op.execute(
        """
        DELETE FROM messages
        USING chats
        WHERE messages.chat_id = chats.id
          AND chats.type IN ('group', 'supergroup', 'channel')
          AND messages.source_snapshot = '{}'::jsonb
        """
    )
    op.execute(
        """
        UPDATE messages
        SET retention_expires_at = messages.telegram_date
            + make_interval(days => chats.retention_days)
        FROM chats
        WHERE messages.chat_id = chats.id
        """
    )
    op.alter_column("messages", "retention_expires_at", nullable=False)
    op.create_check_constraint(
        "message_tombstone_anonymous",
        "messages",
        "privacy_deleted_at IS NULL OR "
        "user_id IS NULL AND content_type::text = 'deleted'::text "
        "AND text = '[message deleted]'::text "
        "AND attachment_type IS NULL AND attachment_file_id IS NULL",
    )
    op.create_index(
        "idx_messages_retention_expiry",
        "messages",
        ["retention_expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_retention_expiry", table_name="messages")
    op.drop_constraint("message_tombstone_anonymous", "messages", type_="check")
    op.drop_column("messages", "retention_expires_at")
    op.drop_column("messages", "privacy_deleted_at")
    # ### end Alembic commands ###
