"""remove legacy chat memory

Revision ID: 9f463771532f
Revises: 11dccab60152
Create Date: 2026-07-20 20:38:40.037626+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9f463771532f"
down_revision: str | None = "11dccab60152"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("llm_memory_max_length", "chats", type_="check")
    op.drop_column("chats", "llm_memory")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats", sa.Column("llm_memory", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_check_constraint(
        "llm_memory_max_length",
        "chats",
        "length(llm_memory) <= 1024",
    )
    # ### end Alembic commands ###
