"""polish telegram conversations

Revision ID: 73987bf19c88
Revises: 89f60115a175
Create Date: 2026-08-03 13:58:15.593000+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "73987bf19c88"
down_revision: str | None = "89f60115a175"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_notices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("notice", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "shown_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(notice::text)) > 0", name="user_notice_name_nonblank"
        ),
        sa.CheckConstraint("version > 0", name="user_notice_version_positive"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "notice"),
    )
    op.create_table(
        "chat_run_receipts",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("request_message_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "response_message_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("model_key", sa.String(length=32), nullable=False),
        sa.Column("model_display_name", sa.String(length=255), nullable=False),
        sa.Column("privacy_mode", sa.String(length=16), nullable=False),
        sa.Column("context_messages", sa.Integer(), nullable=False),
        sa.Column("context_turns", sa.Integer(), nullable=False),
        sa.Column("context_estimated_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(response_message_ids) = 'array'::text AND jsonb_array_length(response_message_ids) > 0",
            name="chat_run_receipt_response_messages_nonempty",
        ),
        sa.CheckConstraint(
            "privacy_mode::text = ANY (ARRAY['private'::text, 'free'::text])",
            name="chat_run_receipt_privacy_mode_allowed",
        ),
        sa.CheckConstraint(
            "context_messages >= 0 AND context_turns >= 0 AND context_estimated_tokens >= 0",
            name="chat_run_receipt_context_nonnegative",
        ),
        sa.CheckConstraint(
            "request_message_id > 0", name="chat_run_receipt_request_message_positive"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["paid_operations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id"),
    )
    op.create_index(
        "idx_chat_run_receipt_chat",
        "chat_run_receipts",
        ["chat_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_run_receipts_chat_id"),
        "chat_run_receipts",
        ["chat_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_run_receipts_requester_id"),
        "chat_run_receipts",
        ["requester_id"],
        unique=False,
    )
    op.create_table(
        "support_intakes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("payment_receipt_id", sa.Uuid(), nullable=True),
        sa.Column("prompt_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("prompt_message_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind::text = ANY (ARRAY['payment'::text, 'refund'::text, 'privacy'::text, 'access'::text])",
            name="support_intake_kind_allowed",
        ),
        sa.CheckConstraint(
            "payment_receipt_id IS NULL OR kind::text = ANY (ARRAY['payment'::text, 'refund'::text])",
            name="support_intake_payment_kind_matches",
        ),
        sa.CheckConstraint(
            "source::text = ANY (ARRAY['support'::text, 'paysupport'::text, 'privacy'::text])",
            name="support_intake_source_allowed",
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name="support_intake_expiry_after_creation"
        ),
        sa.CheckConstraint(
            "prompt_chat_id <> 0 AND prompt_message_id > 0",
            name="support_intake_prompt_valid",
        ),
        sa.ForeignKeyConstraint(
            ["payment_receipt_id"], ["payment_receipts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "prompt_chat_id", "prompt_message_id", name="support_intake_prompt_unique"
        ),
    )
    op.create_index(
        "idx_support_intake_expiry", "support_intakes", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_support_intakes_requester_user_id"),
        "support_intakes",
        ["requester_user_id"],
        unique=False,
    )
    op.add_column(
        "chats",
        sa.Column(
            "free_inference_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "chats",
        sa.Column(
            "free_inference_revision",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "chats",
        sa.Column("free_inference_tos_version", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "chats",
        sa.Column(
            "free_inference_privacy_version", sa.String(length=64), nullable=True
        ),
    )
    op.add_column(
        "chats",
        sa.Column("free_inference_accepted_by_user_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "chats",
        sa.Column(
            "free_inference_accepted_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "chats",
        sa.Column(
            "free_inference_revoked_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_foreign_key(
        "fk_chats_free_inference_accepted_by_user",
        "chats",
        "users",
        ["free_inference_accepted_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "chat_free_inference_revision_positive",
        "chats",
        "free_inference_revision > 0",
    )
    op.create_check_constraint(
        "chat_free_inference_acceptance_complete",
        "chats",
        "num_nonnulls(free_inference_tos_version, "
        "free_inference_privacy_version, free_inference_accepted_by_user_id, "
        "free_inference_accepted_at) = ANY (ARRAY[0, 4])",
    )
    op.create_check_constraint(
        "chat_free_inference_versions_nonblank",
        "chats",
        "coalesce(length(btrim(free_inference_tos_version::text)), 1) > 0 "
        "AND coalesce(length(btrim(free_inference_privacy_version::text)), 1) > 0",
    )
    op.create_check_constraint(
        "chat_free_inference_state_complete",
        "chats",
        "free_inference_enabled = false AND "
        "(free_inference_accepted_at IS NULL AND free_inference_revoked_at IS NULL "
        "OR free_inference_accepted_at IS NOT NULL AND "
        "free_inference_revoked_at IS NOT NULL) OR "
        "free_inference_enabled = true AND free_inference_accepted_at IS NOT NULL "
        "AND free_inference_revoked_at IS NULL",
    )
    op.create_check_constraint(
        "chat_free_inference_revocation_order",
        "chats",
        "free_inference_revoked_at IS NULL OR "
        "free_inference_revoked_at >= free_inference_accepted_at",
    )
    op.drop_index(
        "support_request_one_open_kind_per_user",
        table_name="support_requests",
    )
    op.drop_constraint(
        "support_request_resolution_complete",
        "support_requests",
        type_="check",
    )
    op.drop_constraint(
        "support_request_status_allowed",
        "support_requests",
        type_="check",
    )
    op.add_column(
        "support_requests", sa.Column("description", sa.Text(), nullable=True)
    )
    op.add_column(
        "support_requests", sa.Column("payment_receipt_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "support_requests", sa.Column("decision_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "support_requests",
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "support_requests",
        sa.Column("operator_telegram_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "support_requests",
        sa.Column("status_message_chat_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "support_requests",
        sa.Column("status_message_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "support_requests",
        sa.Column("content_purged_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_support_requests_payment_receipt_id"),
        "support_requests",
        ["payment_receipt_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_support_requests_payment_receipt",
        "support_requests",
        "payment_receipts",
        ["payment_receipt_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "support_request_status_allowed",
        "support_requests",
        "status::text = ANY (ARRAY['open'::text, 'refund_pending'::text, "
        "'resolved'::text, 'declined'::text])",
    )
    op.create_check_constraint(
        "support_request_resolution_complete",
        "support_requests",
        "status::text = ANY (ARRAY['open'::text, 'refund_pending'::text]) "
        "AND resolved_at IS NULL OR status::text = ANY "
        "(ARRAY['resolved'::text, 'declined'::text]) AND resolved_at IS NOT NULL",
    )
    op.create_check_constraint(
        "support_request_description_bounded",
        "support_requests",
        "description IS NULL OR "
        "char_length(btrim(description::text)) BETWEEN 1 AND 800",
    )
    op.create_check_constraint(
        "support_request_decision_reason_bounded",
        "support_requests",
        "decision_reason IS NULL OR "
        "char_length(btrim(decision_reason::text)) BETWEEN 1 AND 800",
    )
    op.create_check_constraint(
        "support_request_status_message_complete",
        "support_requests",
        "num_nonnulls(status_message_chat_id, status_message_id) = ANY (ARRAY[0, 2])",
    )
    op.create_check_constraint(
        "support_request_payment_kind_matches",
        "support_requests",
        "payment_receipt_id IS NULL OR kind::text = ANY "
        "(ARRAY['payment'::text, 'refund'::text])",
    )
    op.create_index(
        "support_request_one_open_kind_per_user",
        "support_requests",
        ["requester_user_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status IN ('open', 'refund_pending')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "support_request_one_open_kind_per_user",
        table_name="support_requests",
    )
    for constraint in (
        "support_request_payment_kind_matches",
        "support_request_status_message_complete",
        "support_request_decision_reason_bounded",
        "support_request_description_bounded",
        "support_request_resolution_complete",
        "support_request_status_allowed",
    ):
        op.drop_constraint(constraint, "support_requests", type_="check")
    op.execute(
        "UPDATE support_requests "
        "SET status = 'open', resolved_at = NULL "
        "WHERE status = 'refund_pending'"
    )
    op.execute(
        "UPDATE support_requests "
        "SET status = 'resolved', "
        "resolved_at = coalesce(resolved_at, decided_at, now()) "
        "WHERE status = 'declined'"
    )
    op.drop_constraint(
        "fk_support_requests_payment_receipt",
        "support_requests",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_support_requests_payment_receipt_id"), table_name="support_requests"
    )
    op.drop_column("support_requests", "content_purged_at")
    op.drop_column("support_requests", "status_message_id")
    op.drop_column("support_requests", "status_message_chat_id")
    op.drop_column("support_requests", "operator_telegram_id")
    op.drop_column("support_requests", "decided_at")
    op.drop_column("support_requests", "decision_reason")
    op.drop_column("support_requests", "payment_receipt_id")
    op.drop_column("support_requests", "description")
    op.create_check_constraint(
        "support_request_status_allowed",
        "support_requests",
        "status::text = ANY (ARRAY['open'::text, 'resolved'::text])",
    )
    op.create_check_constraint(
        "support_request_resolution_complete",
        "support_requests",
        "status::text = 'open'::text AND resolved_at IS NULL OR "
        "status::text = 'resolved'::text AND resolved_at IS NOT NULL",
    )
    op.create_index(
        "support_request_one_open_kind_per_user",
        "support_requests",
        ["requester_user_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    for constraint in (
        "chat_free_inference_revocation_order",
        "chat_free_inference_state_complete",
        "chat_free_inference_versions_nonblank",
        "chat_free_inference_acceptance_complete",
        "chat_free_inference_revision_positive",
    ):
        op.drop_constraint(constraint, "chats", type_="check")
    op.drop_constraint(
        "fk_chats_free_inference_accepted_by_user",
        "chats",
        type_="foreignkey",
    )
    op.drop_column("chats", "free_inference_revoked_at")
    op.drop_column("chats", "free_inference_accepted_at")
    op.drop_column("chats", "free_inference_accepted_by_user_id")
    op.drop_column("chats", "free_inference_privacy_version")
    op.drop_column("chats", "free_inference_tos_version")
    op.drop_column("chats", "free_inference_revision")
    op.drop_column("chats", "free_inference_enabled")
    op.drop_index(
        op.f("ix_support_intakes_requester_user_id"), table_name="support_intakes"
    )
    op.drop_index("idx_support_intake_expiry", table_name="support_intakes")
    op.drop_table("support_intakes")
    op.drop_index(
        op.f("ix_chat_run_receipts_requester_id"), table_name="chat_run_receipts"
    )
    op.drop_index(op.f("ix_chat_run_receipts_chat_id"), table_name="chat_run_receipts")
    op.drop_index("idx_chat_run_receipt_chat", table_name="chat_run_receipts")
    op.drop_table("chat_run_receipts")
    op.drop_table("user_notices")
    # ### end Alembic commands ###
