"""add OpenRouter inference governance

Revision ID: 98772896c1f4
Revises: 5e6b666d0b7a
Create Date: 2026-07-21 14:12:30.741604+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "98772896c1f4"
down_revision: str | None = "5e6b666d0b7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inference_usage_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("provider_model_id", sa.String(length=255), nullable=False),
        sa.Column("provider_response_id", sa.String(length=255), nullable=True),
        sa.Column("provider_generation_id", sa.String(length=255), nullable=True),
        sa.Column(
            "input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "output_tokens",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total_tokens", sa.BigInteger(), nullable=True),
        sa.Column(
            "cache_read_tokens",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "cache_write_tokens",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "reasoning_tokens",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "audio_input_tokens",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "audio_output_tokens",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "usage_available",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("actual_cost_usd", sa.Numeric(precision=20, scale=12), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "reconciliation_status",
            sa.String(length=16),
            server_default=sa.text("'not_ready'"),
            nullable=False,
        ),
        sa.Column("provider_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reconciliation_requested_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "reconciliation_retry_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("reconciliation_claim_token", sa.Uuid(), nullable=True),
        sa.Column(
            "reconciliation_claimed_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "reconciliation_lease_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "reconciliation_attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(reconciliation_status::text = 'not_ready'::text AND reconciliation_requested_at IS NULL AND reconciled_at IS NULL AND actual_cost_usd IS NULL AND reconciliation_retry_at IS NULL AND reconciliation_claim_token IS NULL AND reconciliation_attempts = 0) OR (reconciliation_status::text = 'pending'::text AND reconciliation_requested_at IS NOT NULL AND reconciled_at IS NULL AND actual_cost_usd IS NULL) OR (reconciliation_status::text = 'reconciled'::text AND reconciliation_requested_at IS NOT NULL AND reconciled_at IS NOT NULL AND actual_cost_usd IS NOT NULL AND reconciliation_retry_at IS NULL AND reconciliation_claim_token IS NULL) OR (reconciliation_status::text = 'unavailable'::text AND reconciled_at IS NULL AND actual_cost_usd IS NULL AND reconciliation_retry_at IS NULL AND reconciliation_claim_token IS NULL)",
            name="inference_usage_reconciliation_state_matches",
        ),
        sa.CheckConstraint(
            "(status::text = 'pending'::text AND provider_completed_at IS NULL AND usage_recorded_at IS NULL AND provider_response_id IS NULL AND provider_generation_id IS NULL AND NOT usage_available AND reconciliation_status::text = 'not_ready'::text) OR (status::text = ANY (ARRAY['succeeded'::text, 'failed'::text]) AND provider_completed_at IS NOT NULL AND usage_recorded_at IS NOT NULL AND reconciliation_status::text = ANY (ARRAY['pending'::text, 'reconciled'::text, 'unavailable'::text]))",
            name="inference_usage_outcome_state_matches",
        ),
        sa.CheckConstraint(
            "reconciliation_status::text = ANY (ARRAY['not_ready'::text, 'pending'::text, 'reconciled'::text, 'unavailable'::text])",
            name="inference_usage_reconciliation_status_allowed",
        ),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['pending'::text, 'succeeded'::text, 'failed'::text])",
            name="inference_usage_status_allowed",
        ),
        sa.CheckConstraint(
            "actual_cost_usd IS NULL OR actual_cost_usd >= 0::numeric",
            name="inference_usage_actual_cost_non_negative",
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND reasoning_tokens >= 0 AND audio_input_tokens >= 0 AND audio_output_tokens >= 0 AND (total_tokens IS NULL OR total_tokens >= 0)",
            name="inference_usage_tokens_non_negative",
        ),
        sa.CheckConstraint(
            "length(btrim(provider::text)) > 0 AND length(btrim(provider_model_id::text)) > 0",
            name="inference_usage_provider_fields_not_blank",
        ),
        sa.CheckConstraint(
            "provider_completed_at IS NULL OR provider_completed_at >= provider_started_at",
            name="inference_usage_provider_time_order",
        ),
        sa.CheckConstraint(
            "provider_generation_id IS NULL OR length(btrim(provider_generation_id::text)) > 0",
            name="inference_usage_generation_id_not_blank",
        ),
        sa.CheckConstraint(
            "provider_response_id IS NULL OR length(btrim(provider_response_id::text)) > 0",
            name="inference_usage_response_id_not_blank",
        ),
        sa.CheckConstraint(
            "reconciled_at IS NULL OR (reconciliation_requested_at IS NOT NULL AND reconciled_at >= reconciliation_requested_at)",
            name="inference_usage_reconciled_requires_request",
        ),
        sa.CheckConstraint(
            "reconciliation_requested_at IS NULL OR (usage_recorded_at IS NOT NULL AND reconciliation_requested_at >= usage_recorded_at)",
            name="inference_usage_reconciliation_requires_usage",
        ),
        sa.CheckConstraint(
            "reconciliation_attempts >= 0",
            name="inference_usage_reconciliation_attempts_non_negative",
        ),
        sa.CheckConstraint(
            "num_nonnulls(reconciliation_claim_token, reconciliation_claimed_at, reconciliation_lease_expires_at) = ANY (ARRAY[0, 3])",
            name="inference_usage_reconciliation_claim_complete",
        ),
        sa.CheckConstraint(
            "reconciliation_claimed_at IS NULL OR (reconciliation_requested_at IS NOT NULL AND reconciliation_claimed_at >= reconciliation_requested_at AND reconciliation_lease_expires_at > reconciliation_claimed_at)",
            name="inference_usage_reconciliation_claim_time_order",
        ),
        sa.CheckConstraint(
            "reconciliation_retry_at IS NULL OR (reconciliation_status::text = 'pending'::text AND reconciliation_requested_at IS NOT NULL AND reconciliation_retry_at >= reconciliation_requested_at)",
            name="inference_usage_reconciliation_retry_pending",
        ),
        sa.CheckConstraint(
            "reconciliation_claim_token IS NULL OR reconciliation_retry_at IS NULL",
            name="inference_usage_reconciliation_claim_not_deferred",
        ),
        sa.CheckConstraint(
            "usage_available OR (input_tokens = 0 AND output_tokens = 0 AND total_tokens IS NULL AND cache_read_tokens = 0 AND cache_write_tokens = 0 AND reasoning_tokens = 0 AND audio_input_tokens = 0 AND audio_output_tokens = 0)",
            name="inference_usage_unavailable_tokens_empty",
        ),
        sa.CheckConstraint(
            "usage_recorded_at IS NULL OR usage_recorded_at >= provider_started_at",
            name="inference_usage_recorded_time_order",
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["operation_id"], ["paid_operations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_inference_usage_chat",
        "inference_usage_records",
        ["chat_id", "provider_started_at"],
        unique=False,
    )
    op.create_index(
        "idx_inference_usage_operation",
        "inference_usage_records",
        ["operation_id", "provider_started_at"],
        unique=False,
    )
    op.create_index(
        "idx_inference_usage_provider_generation",
        "inference_usage_records",
        ["provider", "provider_generation_id"],
        unique=False,
    )
    op.create_index(
        "idx_inference_usage_provider_response",
        "inference_usage_records",
        ["provider", "provider_response_id"],
        unique=False,
    )
    op.create_index(
        "idx_inference_usage_reconciliation",
        "inference_usage_records",
        ["reconciliation_status", "reconciliation_requested_at", "id"],
        unique=False,
    )
    op.create_index(
        "idx_inference_usage_reconciliation_claim",
        "inference_usage_records",
        [
            "provider",
            "reconciliation_status",
            "reconciliation_retry_at",
            "reconciliation_lease_expires_at",
            "reconciliation_requested_at",
            "id",
        ],
        unique=False,
    )
    op.create_index(
        "idx_inference_usage_user",
        "inference_usage_records",
        ["user_id", "provider_started_at"],
        unique=False,
    )
    op.add_column(
        "operation_quotes",
        sa.Column(
            "provider",
            sa.String(length=32),
            server_default=sa.text("'google'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "inference_privacy_mode",
            sa.String(length=32),
            server_default=sa.text("'private_only'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "inference_privacy_revision",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("free_inference_tos_version", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "free_inference_privacy_version", sa.String(length=64), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "free_inference_accepted_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "free_inference_revoked_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_check_constraint(
        "operation_quote_provider_allowed",
        "operation_quotes",
        "provider::text = ANY (ARRAY['openrouter'::text, 'google'::text])",
    )
    op.create_check_constraint(
        "user_inference_privacy_mode_allowed",
        "users",
        "inference_privacy_mode::text = ANY "
        "(ARRAY['private_only'::text, 'allow_non_zdr_free'::text])",
    )
    op.create_check_constraint(
        "user_inference_privacy_revision_positive",
        "users",
        "inference_privacy_revision > 0",
    )
    op.create_check_constraint(
        "user_free_inference_acceptance_complete",
        "users",
        "num_nonnulls(free_inference_tos_version, "
        "free_inference_privacy_version, free_inference_accepted_at) "
        "= ANY (ARRAY[0, 3])",
    )
    op.create_check_constraint(
        "user_free_inference_versions_nonblank",
        "users",
        "coalesce(length(btrim(free_inference_tos_version::text)), 1) > 0 "
        "AND coalesce(length(btrim(free_inference_privacy_version::text)), 1) > 0",
    )
    op.create_check_constraint(
        "user_free_inference_state_complete",
        "users",
        "(inference_privacy_mode::text = 'private_only'::text AND "
        "((free_inference_accepted_at IS NULL AND "
        "free_inference_revoked_at IS NULL) OR "
        "(free_inference_accepted_at IS NOT NULL AND "
        "free_inference_revoked_at IS NOT NULL))) OR "
        "(inference_privacy_mode::text = 'allow_non_zdr_free'::text AND "
        "free_inference_accepted_at IS NOT NULL AND "
        "free_inference_revoked_at IS NULL)",
    )
    op.create_check_constraint(
        "user_free_inference_revocation_order",
        "users",
        "free_inference_revoked_at IS NULL OR "
        "free_inference_revoked_at >= free_inference_accepted_at",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_free_inference_revocation_order", "users", type_="check")
    op.drop_constraint("user_free_inference_state_complete", "users", type_="check")
    op.drop_constraint("user_free_inference_versions_nonblank", "users", type_="check")
    op.drop_constraint(
        "user_free_inference_acceptance_complete", "users", type_="check"
    )
    op.drop_constraint(
        "user_inference_privacy_revision_positive", "users", type_="check"
    )
    op.drop_constraint("user_inference_privacy_mode_allowed", "users", type_="check")
    op.drop_constraint(
        "operation_quote_provider_allowed", "operation_quotes", type_="check"
    )
    op.drop_column("users", "free_inference_revoked_at")
    op.drop_column("users", "free_inference_accepted_at")
    op.drop_column("users", "free_inference_privacy_version")
    op.drop_column("users", "free_inference_tos_version")
    op.drop_column("users", "inference_privacy_revision")
    op.drop_column("users", "inference_privacy_mode")
    op.drop_column("operation_quotes", "provider")
    op.drop_index("idx_inference_usage_user", table_name="inference_usage_records")
    op.drop_index(
        "idx_inference_usage_reconciliation_claim",
        table_name="inference_usage_records",
        if_exists=True,
    )
    op.drop_index(
        "idx_inference_usage_reconciliation", table_name="inference_usage_records"
    )
    op.drop_index(
        "idx_inference_usage_provider_response", table_name="inference_usage_records"
    )
    op.drop_index(
        "idx_inference_usage_provider_generation", table_name="inference_usage_records"
    )
    op.drop_index("idx_inference_usage_operation", table_name="inference_usage_records")
    op.drop_index("idx_inference_usage_chat", table_name="inference_usage_records")
    op.drop_table("inference_usage_records")
    # ### end Alembic commands ###
