"""add topic scoped shared facts

Revision ID: 11dccab60152
Revises: 02b5064d13e8
Create Date: 2026-07-20 20:24:45.439272+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "11dccab60152"
down_revision: str | None = "02b5064d13e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("fact_text", sa.Text(), nullable=False),
        sa.Column(
            "state",
            sa.String(length=16),
            server_default=sa.text("'proposed'"),
            nullable=False,
        ),
        sa.Column("proposed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state::text = 'proposed'::text AND decided_by_user_id IS NULL AND decided_at IS NULL OR (state::text = ANY (ARRAY['approved'::text, 'rejected'::text])) AND decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL",
            name="shared_fact_decision_complete",
        ),
        sa.CheckConstraint(
            "state::text = ANY (ARRAY['proposed'::text, 'approved'::text, 'rejected'::text])",
            name="shared_fact_state_allowed",
        ),
        sa.CheckConstraint(
            "length(btrim(fact_text)) > 0", name="shared_fact_text_not_blank"
        ),
        sa.CheckConstraint(
            "length(fact_text) <= 1024", name="shared_fact_text_max_length"
        ),
        sa.CheckConstraint(
            "thread_id IS NULL OR thread_id > 0", name="shared_fact_thread_id_positive"
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_shared_facts_scope_approved",
        "shared_facts",
        ["chat_id", "thread_id", "created_at", "id"],
        unique=False,
        postgresql_where="state = 'approved'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_shared_facts_scope_approved",
        table_name="shared_facts",
        postgresql_where="state = 'approved'",
    )
    op.drop_table("shared_facts")
    # ### end Alembic commands ###
